# jekyll 基本定義黨
# Site settings
title: LinLi Web Page
email: standleylin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lin Li web page
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lllllinli
github_username:  lllllinli

# Build settings
markdown: kramdown
